from gameplay.entities.visuals.cosmetics import (
    Blood,
    ConversationBubbles,
    Dust,
    Dusts,
    EnemySpawnEffect,
    Grass,
    InteractableIndicator,
    PlayerSoul,
    PlayerSpawnEffect,
    PrayEffect,
    RuneSymbol,
    ShockWave,
    Slash,
    Smoke,
    ThunderBall,
    ThunderSpark,
    Twinkle,
    Water,
)


REGISTER_COSMETICS = {
    "blood": Blood,
    "conversation_bubbles": ConversationBubbles,
    "dust": Dust,
    "dusts": Dusts,
    "enemy_spawn_effect": EnemySpawnEffect,
    "grass": Grass,
    "interactable_indicator": InteractableIndicator,
    "player_spawn_effect": PlayerSpawnEffect,
    "player_soul": PlayerSoul,
    "pray_effect": PrayEffect,
    "rune_symbol": RuneSymbol,
    "shock_wave": ShockWave,
    "slash": Slash,
    "smoke": Smoke,
    "thunder_ball": ThunderBall,
    "thunder_spark": ThunderSpark,
    "twinkle": Twinkle,
    "water": Water,
}
