from gameplay.entities.enemies import *

REGISTER_ENEMIES = {
    'reindeer': Reindeer,
    'rhoutta_encounter': RhouttaEncounter,
    'butterfly': Butterfly,
    'bird': Bird,
    'flower_butterfly': FlowerButterfly,
    'mygga_chase': MyggaChase,
    'mygga_colliding_projectile': MyggaCollidingProjectile,
    'mygga_colliding': MyggaColliding,
    'mygga_crystal': MyggaCrystal,
    'mygga_exploding': MyggaExploding,
    'mygga_suicide': MyggaSuicide,
    'mygga_torpedo': MyggaTorpedo,
    'mygga': Mygga,
    'crab_crystal': CrabCrystal,
    'egg': Egg,
    'froggy': Froggy,
    'kusa': Kusa,
    'packun': Packun,
    'rav': Rav,
    'sandrew': Sandrew,
    'shroompoline': Shroompoline,
    'svampis': Svampis,
    'vatt': Vatt,
    'wild_swine': WildSwine,
    'maggot': Maggot,
    'cultist_rogue': CultistRogue,
    'cultist_warrior': CultistWarrior,
    'larv_jr': LarvJr,
    'larv_poison': LarvPoison,
    'larv_wall': LarvWall,
    'larv': Larv,
    'shadow_warrior': ShadowWarrior,

}